# App Engine configuration
runtime: nodejs18

# Instance class (F1 = free tier, F2/F4 = more resources)
instance_class: F2

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6

# Environment variables (non-sensitive only)
env_variables:
  NODE_ENV: "production"
  USE_CLOUD_STORAGE: "true"
  USE_GOOGLE_TTS: "true"
  GCS_PROJECT_ID: "podcast-generator-474105"
  GCS_DOCUMENTS_BUCKET: "podcast-documents-474105"
  GCS_AUDIO_BUCKET: "podcast-audio-474105"
  GCS_LOCATION: "us-central1"
  GCS_SIGNED_URL_EXPIRATION: "3600"
  GOOGLE_CLOUD_PROJECT_ID: "podcast-generator-474105"
  GOOGLE_CLOUD_LOCATION: "us"
  VERTEX_AI_PROJECT_ID: "podcast-generator-474105"
  VERTEX_AI_LOCATION: "us-central1"
  PORT: "8080"

# Handlers for static files (optional)
handlers:
  # Serve static files from css/ directory
  - url: /css
    static_dir: css
    secure: always

  # Serve static files from js/ directory
  - url: /js
    static_dir: js
    secure: always

  # Serve HTML files
  - url: /(.*\.(html|ico|txt))$
    static_files: \1
    upload: .*\.(html|ico|txt)$
    secure: always

  # Route all other requests to Node.js app
  - url: /.*
    script: auto
    secure: always

# Files to skip during deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^node_modules/(?!.*production).*$
  - ^uploads/.*$
  - ^uploads-backup.*/.*$
  - ^test/.*$
  - ^.*\.md$
  - ^.*\.log$
  - \.gitignore
  - \.dockerignore
  - Dockerfile
  - cloudbuild.yaml
  - migrate-.*\.js$
  - test-.*\.js$
  - cleanup-.*\.js$
  - check-.*\.js$
  - setup-.*\.js$
